# Generated by Django 5.0.6 on 2024-06-04 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('HU', 'Humano'), ('FI', 'Financiero'), ('MA', 'Material'), ('TE', 'Técnico')], default='MA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('SO', 'Solicitado'), ('CO', 'Concedido'), ('US', 'En uso'), ('FI', 'Finalizado')], default='SO', max_length=2)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recursos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'order_with_respect_to': 'user',
            },
        ),
    ]
